"""Add temporary_shifts table

Revision ID: 16e48923bf26
Revises: 43c51c24c7da
Create Date: 2026-01-13 20:47:51.060459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e48923bf26'
down_revision = '43c51c24c7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.alter_column('Emp ID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.alter_column('Emp ID',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('temporary_shifts')
    # ### end Alembic commands ###
