"""Initial migration

Revision ID: 43c51c24c7da
Revises: 
Create Date: 2025-12-29 23:39:53.403507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c51c24c7da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('applied_day', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uix_emp_date', ['emp_id', 'date'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_employees_department'))
        batch_op.drop_index(batch_op.f('idx_employees_emp_id'))
        batch_op.drop_index(batch_op.f('idx_employees_role'))
        batch_op.create_unique_constraint(None, ['emp_id'])

    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_leave', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('casual_leave', sa.Integer(), nullable=True))
        batch_op.alter_column('punch_missed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.alter_column('punch_missed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('casual_leave')
        batch_op.drop_column('medical_leave')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_employees_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_employees_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_employees_department'), ['department'], unique=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.drop_constraint('uix_emp_date', type_='unique')
        batch_op.drop_column('leave_type')

    op.drop_table('leave_applications')
    # ### end Alembic commands ###
