"""empty message

Revision ID: 8e21cafaddba
Revises: cabc78d5193d
Create Date: 2025-12-02 07:45:00.630184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e21cafaddba'
down_revision = 'cabc78d5193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_day_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.drop_table('employee_shifts')
    op.drop_table('company_off')
    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_raw_name')
        batch_op.drop_index('idx_attendance_raw_time')

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compensation_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('compensated_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_company_off', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_off_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_day', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.alter_column('shift',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index('idx_daily_report_emp_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['emp_id'])

    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_off_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('by_late_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('by_half_day_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('by_absent_count', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.drop_column('saturday_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturday_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.drop_column('by_absent_count')
        batch_op.drop_column('by_half_day_count')
        batch_op.drop_column('by_late_count')
        batch_op.drop_column('company_off_days')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.create_index('idx_daily_report_emp_id', ['emp_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('shift',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.alter_column('employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('emp_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('working_day')
        batch_op.drop_column('company_off_reason')
        batch_op.drop_column('is_company_off')
        batch_op.drop_column('compensated_date')
        batch_op.drop_column('compensation_type')

    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_raw_time', ['Time'], unique=False)
        batch_op.create_index('idx_attendance_raw_name', ['Name'], unique=False)

    op.create_table('company_off',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('off_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_off_pkey'),
    sa.UniqueConstraint('off_date', name='company_off_off_date_key')
    )
    op.create_table('employee_shifts',
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ID', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Joining Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Shift', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('company_day_off')
    # ### end Alembic commands ###
