"""Fix DailyReport for PostgreSQL - remove autoincrement

Revision ID: cabc78d5193d
Revises: 
Create Date: 2025-12-01 18:47:11.281523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabc78d5193d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('last_updated_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('compensation_type', sa.String(length=20), nullable=True),
    sa.Column('compensated_date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('is_company_off', sa.Boolean(), nullable=True),
    sa.Column('company_off_reason', sa.String(length=200), nullable=True),
    sa.Column('working_day', sa.Boolean(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('missed_checkin', sa.Boolean(), nullable=True),
    sa.Column('missed_checkout', sa.Boolean(), nullable=True),
    sa.Column('overtime', sa.Float(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendance_raw_name'))
        batch_op.drop_index(batch_op.f('idx_attendance_raw_time'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_employee_emp_id'))
        batch_op.create_unique_constraint(None, ['emp_id'])

    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.drop_column('saturday_hours')
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saturday_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FullTime'::character varying"))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_employee_emp_id'), ['emp_id'], unique=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_raw_time'), ['Time'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_raw_name'), ['Name'], unique=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('daily_report')
    # ### end Alembic commands ###
