"""Initial migration

Revision ID: fb44c99e2ffa
Revises: 
Create Date: 2025-12-05 07:05:36.748905

"""
from alembic import op
import sqlalchemy as sa     


# revision identifiers, used by Alembic.
revision = 'fb44c99e2ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_off')
    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendance_raw_name'))
        batch_op.drop_index(batch_op.f('idx_attendance_raw_time'))

    with op.batch_alter_table('company_day_off', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.alter_column('shift',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_daily_report_emp_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint(None, ['emp_id'])

    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.drop_column('working_days')
        batch_op.drop_column('saturday_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturday_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('working_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FullTime'::character varying"))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('emp_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_daily_report_emp_id'), ['emp_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('shift',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FullTime'::character varying"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('company_day_off', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('attendance_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_raw_time'), ['Time'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_raw_name'), ['Name'], unique=False)

    op.create_table('company_off',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('off_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('company_off_pkey')),
    sa.UniqueConstraint('off_date', name=op.f('company_off_off_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
